name: Produire l'ICS et l'ICAL

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  "0 1 * * *"
  workflow_dispatch:

env:
  RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2
    - name: Lancer le script R
      run: Rscript calendrier.R
    - name: Uploader l'ics
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -f edt.ics
        git stash
        git checkout ics
        git stash pop
        git commit -m "Ajout ics"
        git push origin ics
